project: "amqp-agent"
database:
    dialect: "mysql"
    host: "localhost"
    port: 3306
    database: "amqp-agent"
    user: "root"
    password: "root"
    charset: "utf8mb4"
    maxidleconnnum: 1
    maxopenconnnum: 100
mq:
    host: "localhost"
    port: 5672
    user: "guest"
    password: "guest"
    min: 1
    max: 100